name: Run Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make template script executable
        run: chmod +x src/template.sh

      - name: Install BATS and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      - name: Run tests
        run: bats test/template.bats